config/routes.rb
Rails.application.routes.draw do
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#delete'
    get '/login', to: 'sessions#new'
    root 'static_pages#home'
    get '/contact', to: 'static_pages#contact'
    post '/contact', to: 'static_pages#send_contact'

    resources :products, except: [:edit, :update, :show, :new]
    resources :users, only: [:show]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, :description, presence: true
    validate :picture_size

    default_scope -> { order(created_at: :desc) }

    mount_uploader :picture, PictureUploader

    require 'RedCloth'

    def description_html
        RedCloth.new(description).to_html
    end

    private

    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture, 'should be less than 5MB')
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :email, presence: true

    has_secure_password

    def self.create_digest(password)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(password, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def logged_in
        unless logged_in?
            flash[:warning] = 'Please log in.'
            redirect_to login_path
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :logged_in, except: [:index]

    def create
        @product = Product.create(strong_params)
        if @product.save
            flash.now[:success] = 'A product has been created'
            render 'users/show'
        else
            flash.now[:danger] = 'All fields/images need to be filled'
            render 'users/show'
        end
    end

    def index
        @products = Product.all.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @product = Product.find_by(id: params[:id])
        @product.delete
        flash[:success] = 'A product has been deleted'
        redirect_to products_path
    end

    private

    def strong_params
        params.require(:product).permit(:name, :description, :sku, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by(email: params[:session][:email])
        if @user && @user.authenticate(params[:session][:password])
            log_in(@user)
            redirect_to user_path(@user)
        else
            flash.now[:danger] = 'Invalid details.'
            render 'new'
        end
    end

    def new; end

    def delete
        log_out
        redirect_to root_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    # TODO:
    # organise gemfile
    # setup bootrap and jquery

    before_action :check_contact?, only: [:send_contact]

    def home; end

    def contact; end

    def send_contact
        if check_contact?
            ContactMailer.contact_us(@email, body: @body, name: @name).deliver_now
            flash['success'] = 'Thank you for contacting us, we will contact you shortly.'
            redirect_to contact_path
        else
            flash.now[:danger] = 'Please fill in all the details.'
            render 'contact'
        end
    end

    private

    def check_contact?
        @email = params[:contact][:email]
        @name = params[:contact][:name]
        @body = params[:contact][:body]

        !@email.nil? && !@name.nil? && !@body.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in

    def show
        @product = Product.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
        !session[:user_id].nil?
    end

    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def log_out
        session.delete(:user_id)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Manmosu</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render 'shared/header' %>
        <%= render 'shared/flash' %>
        <%= yield %>
        <%= render 'shared/footer' %>
    </body>
</html>

app/views/products/_product.html.erb
<div class="row product">
    <div class="col-md-3">
        <span class="thumbnail">
            <%= image_tag product.picture.url if product.picture? %>
        </span>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <h1 class="panel-heading"><%= product.name %>
                <% if logged_in? %>
                    <%= link_to product_path(product), method: :delete, class:"close", data: { confirm: "Are you sure?" }  do %>
                        <span aria-hidden="true">&times;</span>
                    <%end%>
                <%end%>
            </h1>
            <ul class="list-group">
                <li class="list-group-item">SKU: <%= product.sku %></li>
            </ul>
            <div class="panel-body">
                <%= product.description_html.html_safe %>
            </div>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class=" container container-full black">
    <div class="row">
        <div class="col-md-12 col-centered">
            <img src="<%= asset_path('product-page.png')%>" />
        </div>
    </div>
</div>
<div class="container-full">
    <% if @products.any? %>
        <% @products.each do |product| %>
            <%= render 'products/product', product: product %>
        <%end%>
        <%= will_paginate @products %>
    <%end%>
</div>

app/views/shared/_flash.html.erb
<% if !flash.empty? %>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
            <span class="value"><%= value %></span>
        </div>
    <%end%>
<%end %>

app/views/shared/_footer.html.erb
<div class="black container-full footer">
    <div class="row">
        <div class="col-md-6">
            <div class="mission">
                <i class="fa fa-quote-left fa-3x fa-pull-left fa-border fa-inverse" aria-hidden="true"></i>
                To help others to find their goals through meditation
            </div>
        </div>
        <div class="col-md-6" style="margin-top:100px; color:#ccc; font-size:1.3em;">
            ©2010 to 2017 manmosu inc
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="<%= root_path %>">
              <img src="<%= asset_path('brand.svg')%>"  alt="manmosu"/>
        </a>
    </div>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?('/products')%>"><a href="<%= products_path %>">Products</a></li>
                <li class="<%= 'active' if current_page?('/contact')%>"><a href="<%= contact_path %>">Contact us</a></li>
            </ul>
            <% if logged_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= user_path(current_user) %>">Profile</a></li>
                            <li><%= link_to  "Log out", logout_path, method: :delete %></li>
                        </ul>
                    </li>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

app/views/static_pages/contact.html.erb
<div class=" container container-full black">
    <div class="row">
        <div class="col-md-12 col-centered">
            <img src="<%= asset_path('contact-page.png')%>" />
        </div>
    </div>
</div>
<div class="container">
    <div class="row contact">
        <div class="col-md-7 col-centered">
            <h2>Contact us <i class="fa fa-paper-plane"></i></h2>
            <p>
                Let us know your feedback!
            </p>
            <%= form_for :contact, url: contact_path do |f| %>
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control"%>
                <%= f.label :body, "Message" %>
                <%= f.text_area :body, class: "form-control"%>
                <!-- <%= f.submit "Submit" , class:"btn-primary pull-right "%> -->
                <%= button_tag( :class => "btn pull-right") do %>
                    submit <i class="fa fa-paper-plane""></i>
                <% end %>
            <%end%>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class=" container container-full black">
    <div class="row">
        <div class="col-md-12 col-centered">
            <h4>
                Find your inner <b class="peace">peace</b> with manmosu
            </h4>
            <img src="<%= asset_path('home-page1.png')%>" />
        </div>
    </div>
</div>
<div class=" block container container-full white">
    <div class="row">
        <div class="col-md-12 col-centered">
            <ul >
                <li>
                    <i class="fa fa-heart fa-5x"></i>
                    <div>
                        Our goal is to create a healthier and happier
                    </div>
                </li>
                <li>
                    <i class="fa fa-leaf fa-5x"></i>
                    <div>
                        We want to restore calm and serenity to your busy and chaotic life
                    </div>
                </li>
                <li>
                    <i class="fa fa-battery-full fa-5x"></i>
                    <div>
                        Our products are well designed and high quality
                    </div>
                </li>
                <li>
                    <i class="fa fa-smile-o fa-5x"></i>
                    <div>
                        Meditation improves concentration and increases self-awareness
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class=" container container-full black">
    <div class="row">
        <div class="col-md-12 col-centered">
            <img src="<%= asset_path('login-page.png')%>" />
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-9 col-centered">
            <h2>Create Product</h2>
            <%= form_for :product, url:products_path do |f| %>
                <!-- <% if @product.errors.any? %>
                    <% @product.errors.full_messages.each do |error| %>
                        <%= error %>
                    <%end%>
                <%end%> -->
                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
                <%= f.label :sku %>
                <%= f.text_field :sku, class: 'form-control' %>
                <%= f.label :description %> <a href="https://www.promptworks.com/textile">Textile language cheatsheet</a>
                <%= f.text_area :description,rows: 20,  class: 'form-control'%>
                <%= f.submit "Submit", class: 'btn-primary pull-right'%>
            <%end%>
        </div>
    </div>
    <script type="text/javascript">
        $('#product_picture').bind('change', function() {
                                                                                            var size_in_megabytes = this.files[0].size/1024/1024;
                                                                                            if (size_in_megabytes > 5) {
                                                                                              alert('Maximum file size is 5MB. Please choose a smaller file.');
                                                                                            }
                                                                                          });
    </script>
</div>